// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Mqtt.Server.Identity.CosmosDB.Compiled;
using Mqtt.Server.Identity.Data;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ApplicationDbContext), typeof(ApplicationDbContextModel))]