// <auto-generated />
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Cosmos.Storage.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Newtonsoft.Json.Linq;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Mqtt.Server.Identity.CosmosDB.Compiled
{
    [EntityFrameworkInternal]
    public partial class IdentityUserPasskeyEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>",
                typeof(IdentityUserPasskey<string>),
                baseEntityType,
                propertyCount: 3,
                navigationCount: 1,
                foreignKeyCount: 1,
                keyCount: 1);

            var credentialId = runtimeEntityType.AddProperty(
                "CredentialId",
                typeof(byte[]),
                propertyInfo: typeof(IdentityUserPasskey<string>).GetProperty("CredentialId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserPasskey<string>).GetField("<CredentialId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 1024);
            credentialId.SetGetter(
                byte[] (IdentityUserPasskey<string> instance) => IdentityUserPasskeyUnsafeAccessors<string>.CredentialId(instance),
                bool (IdentityUserPasskey<string> instance) => IdentityUserPasskeyUnsafeAccessors<string>.CredentialId(instance) == null);
            credentialId.SetSetter(
                IdentityUserPasskey<string> (IdentityUserPasskey<string> instance, byte[] value) =>
                {
                    IdentityUserPasskeyUnsafeAccessors<string>.CredentialId(instance) = value;
                    return instance;
                });
            credentialId.SetMaterializationSetter(
                IdentityUserPasskey<string> (IdentityUserPasskey<string> instance, byte[] value) =>
                {
                    IdentityUserPasskeyUnsafeAccessors<string>.CredentialId(instance) = value;
                    return instance;
                });
            credentialId.SetAccessors(
                byte[] (IInternalEntry entry) => IdentityUserPasskeyUnsafeAccessors<string>.CredentialId(((IdentityUserPasskey<string>)(entry.Entity))),
                byte[] (IInternalEntry entry) => IdentityUserPasskeyUnsafeAccessors<string>.CredentialId(((IdentityUserPasskey<string>)(entry.Entity))),
                byte[] (IInternalEntry entry) => entry.ReadOriginalValue<byte[]>(credentialId, 0),
                byte[] (IInternalEntry entry) => ((InternalEntityEntry)(entry)).ReadRelationshipSnapshotValue<byte[]>(credentialId, 0));
            credentialId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            credentialId.TypeMapping = CosmosTypeMapping.Default.Clone(
                comparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)(v1)), ((object)(v2))),
                    int (byte[] v) => ((object)v).GetHashCode(),
                    byte[] (byte[] v) => v),
                keyComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)(v1)), ((object)(v2))),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)(v))),
                    byte[] (byte[] source) => source.ToArray()),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                converter: new ValueConverter<byte[], string>(
                    string (byte[] v) => Convert.ToBase64String(v),
                    byte[] (string v) => Convert.FromBase64String(v)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<byte[], string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<byte[], string>(
                        string (byte[] v) => Convert.ToBase64String(v),
                        byte[] (string v) => Convert.FromBase64String(v))));
            credentialId.SetCurrentValueComparer(new StructuralEntryCurrentValueComparer(credentialId));
            credentialId.AddAnnotation("Cosmos:PropertyName", "id");

            var userId = runtimeEntityType.AddProperty(
                "UserId",
                typeof(string),
                propertyInfo: typeof(IdentityUserPasskey<string>).GetProperty("UserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserPasskey<string>).GetField("<UserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            userId.SetGetter(
                string (IdentityUserPasskey<string> instance) => IdentityUserPasskeyUnsafeAccessors<string>.UserId(instance),
                bool (IdentityUserPasskey<string> instance) => IdentityUserPasskeyUnsafeAccessors<string>.UserId(instance) == null);
            userId.SetSetter(
                IdentityUserPasskey<string> (IdentityUserPasskey<string> instance, string value) =>
                {
                    IdentityUserPasskeyUnsafeAccessors<string>.UserId(instance) = value;
                    return instance;
                });
            userId.SetMaterializationSetter(
                IdentityUserPasskey<string> (IdentityUserPasskey<string> instance, string value) =>
                {
                    IdentityUserPasskeyUnsafeAccessors<string>.UserId(instance) = value;
                    return instance;
                });
            userId.SetAccessors(
                string (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(1) ? entry.ReadStoreGeneratedValue<string>(0) : (entry.FlaggedAsTemporary(1) && IdentityUserPasskeyUnsafeAccessors<string>.UserId(((IdentityUserPasskey<string>)(entry.Entity))) == null ? entry.ReadTemporaryValue<string>(0) : IdentityUserPasskeyUnsafeAccessors<string>.UserId(((IdentityUserPasskey<string>)(entry.Entity))))),
                string (IInternalEntry entry) => IdentityUserPasskeyUnsafeAccessors<string>.UserId(((IdentityUserPasskey<string>)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(userId, 1),
                string (IInternalEntry entry) => ((InternalEntityEntry)(entry)).ReadRelationshipSnapshotValue<string>(userId, 1));
            userId.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: 0);
            userId.TypeMapping = CosmosTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                clrType: typeof(string),
                jsonValueReaderWriter: JsonStringReaderWriter.Instance);
            userId.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(userId));

            var __jObject = runtimeEntityType.AddProperty(
                "__jObject",
                typeof(JObject),
                nullable: true,
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore);
            __jObject.SetAccessors(
                JObject (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(2) ? entry.ReadStoreGeneratedValue<JObject>(1) : (entry.FlaggedAsTemporary(2) && entry.ReadShadowValue<JObject>(0) == null ? entry.ReadTemporaryValue<JObject>(1) : entry.ReadShadowValue<JObject>(0))),
                JObject (IInternalEntry entry) => entry.ReadShadowValue<JObject>(0),
                JObject (IInternalEntry entry) => entry.ReadOriginalValue<JObject>(__jObject, 2),
                JObject (IInternalEntry entry) => entry.GetCurrentValue<JObject>(__jObject));
            __jObject.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: 0,
                relationshipIndex: -1,
                storeGenerationIndex: 1);
            __jObject.TypeMapping = CosmosTypeMapping.Default.Clone(
                comparer: new ValueComparer<JObject>(
                    bool (JObject v1, JObject v2) => object.Equals(v1, v2),
                    int (JObject v) => ((object)v).GetHashCode(),
                    JObject (JObject v) => v),
                keyComparer: new ValueComparer<JObject>(
                    bool (JObject v1, JObject v2) => object.Equals(v1, v2),
                    int (JObject v) => ((object)v).GetHashCode(),
                    JObject (JObject v) => v),
                providerValueComparer: new ValueComparer<JObject>(
                    bool (JObject v1, JObject v2) => object.Equals(v1, v2),
                    int (JObject v) => ((object)v).GetHashCode(),
                    JObject (JObject v) => v),
                clrType: typeof(JObject));
            __jObject.AddAnnotation("Cosmos:PropertyName", "");

            var key = runtimeEntityType.AddKey(
                new[] { credentialId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var credentialId = runtimeEntityType.FindProperty("CredentialId");
            var userId = runtimeEntityType.FindProperty("UserId");
            var __jObject = runtimeEntityType.FindProperty("__jObject");
            var key = runtimeEntityType.FindKey(new[] { credentialId });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNullableFactory<byte[], int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<byte[]>(key));
            var data = runtimeEntityType.FindNavigation("Data");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityUserPasskey<string>)(source.Entity));
                    return ((ISnapshot)(new Snapshot<byte[], string, JObject>((source.GetCurrentValue<byte[]>(credentialId) == null ? null : ((ValueComparer<byte[]>)(((IProperty)credentialId).GetValueComparer())).Snapshot(source.GetCurrentValue<byte[]>(credentialId))), (source.GetCurrentValue<string>(userId) == null ? null : ((ValueComparer<string>)(((IProperty)userId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(userId))), (source.GetCurrentValue<JObject>(__jObject) == null ? null : ((ValueComparer<JObject>)(((IProperty)__jObject).GetValueComparer())).Snapshot(source.GetCurrentValue<JObject>(__jObject))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<string, JObject>((default(string) == null ? null : ((ValueComparer<string>)(((IProperty)userId).GetValueComparer())).Snapshot(default(string))), (default(JObject) == null ? null : ((ValueComparer<JObject>)(((IProperty)__jObject).GetValueComparer())).Snapshot(default(JObject)))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<string, JObject>(default(string), default(JObject)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => ((ISnapshot)(new Snapshot<JObject>((source.ContainsKey("__jObject") ? ((JObject)(source["__jObject"])) : null)))));
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<JObject>(default(JObject)))));
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityUserPasskey<string>)(source.Entity));
                    return ((ISnapshot)(new Snapshot<byte[], string, object>((source.GetCurrentValue<byte[]>(credentialId) == null ? null : ((ValueComparer<byte[]>)(((IProperty)credentialId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<byte[]>(credentialId))), (source.GetCurrentValue<string>(userId) == null ? null : ((ValueComparer<string>)(((IProperty)userId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(userId))), source.GetCurrentValue<IdentityPasskeyData>(data))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 3,
                navigationCount: 1,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 3,
                shadowCount: 1,
                relationshipCount: 3,
                storeGeneratedCount: 2));
            runtimeEntityType.AddAnnotation("Cosmos:ContainerName", "Identity_UserPasskeys");
            runtimeEntityType.AddAnnotation("Cosmos:PartitionKeyNames", new List<string> { "UserId" });
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AspNetUserPasskeys");

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}