// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Cosmos.Storage.Internal;
using Microsoft.EntityFrameworkCore.Cosmos.ValueGeneration.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Newtonsoft.Json.Linq;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Mqtt.Server.Identity.CosmosDB.Compiled
{
    [EntityFrameworkInternal]
    public partial class IdentityUserTokenEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Microsoft.AspNetCore.Identity.IdentityUserToken<string>",
                typeof(IdentityUserToken<string>),
                baseEntityType,
                propertyCount: 6,
                foreignKeyCount: 1,
                keyCount: 1);

            var userId = runtimeEntityType.AddProperty(
                "UserId",
                typeof(string),
                propertyInfo: typeof(IdentityUserToken<string>).GetProperty("UserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserToken<string>).GetField("<UserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            userId.SetGetter(
                string (IdentityUserToken<string> entity) => IdentityUserTokenUnsafeAccessors<string>.UserId(entity),
                bool (IdentityUserToken<string> entity) => IdentityUserTokenUnsafeAccessors<string>.UserId(entity) == null,
                string (IdentityUserToken<string> instance) => IdentityUserTokenUnsafeAccessors<string>.UserId(instance),
                bool (IdentityUserToken<string> instance) => IdentityUserTokenUnsafeAccessors<string>.UserId(instance) == null);
            userId.SetSetter(
                (IdentityUserToken<string> entity, string value) => IdentityUserTokenUnsafeAccessors<string>.UserId(entity) = value);
            userId.SetMaterializationSetter(
                (IdentityUserToken<string> entity, string value) => IdentityUserTokenUnsafeAccessors<string>.UserId(entity) = value);
            userId.SetAccessors(
                string (InternalEntityEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<string>(0) : (entry.FlaggedAsTemporary(0) && IdentityUserTokenUnsafeAccessors<string>.UserId(((IdentityUserToken<string>)(entry.Entity))) == null ? entry.ReadTemporaryValue<string>(0) : IdentityUserTokenUnsafeAccessors<string>.UserId(((IdentityUserToken<string>)(entry.Entity))))),
                string (InternalEntityEntry entry) => IdentityUserTokenUnsafeAccessors<string>.UserId(((IdentityUserToken<string>)(entry.Entity))),
                string (InternalEntityEntry entry) => entry.ReadOriginalValue<string>(userId, 0),
                string (InternalEntityEntry entry) => entry.ReadRelationshipSnapshotValue<string>(userId, 0),
                object (ValueBuffer valueBuffer) => valueBuffer[0]);
            userId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            userId.TypeMapping = CosmosTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                clrType: typeof(string),
                jsonValueReaderWriter: JsonStringReaderWriter.Instance);
            userId.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(userId));

            var loginProvider = runtimeEntityType.AddProperty(
                "LoginProvider",
                typeof(string),
                propertyInfo: typeof(IdentityUserToken<string>).GetProperty("LoginProvider", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserToken<string>).GetField("<LoginProvider>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            loginProvider.SetGetter(
                string (IdentityUserToken<string> entity) => IdentityUserTokenUnsafeAccessors<string>.LoginProvider(entity),
                bool (IdentityUserToken<string> entity) => IdentityUserTokenUnsafeAccessors<string>.LoginProvider(entity) == null,
                string (IdentityUserToken<string> instance) => IdentityUserTokenUnsafeAccessors<string>.LoginProvider(instance),
                bool (IdentityUserToken<string> instance) => IdentityUserTokenUnsafeAccessors<string>.LoginProvider(instance) == null);
            loginProvider.SetSetter(
                (IdentityUserToken<string> entity, string value) => IdentityUserTokenUnsafeAccessors<string>.LoginProvider(entity) = value);
            loginProvider.SetMaterializationSetter(
                (IdentityUserToken<string> entity, string value) => IdentityUserTokenUnsafeAccessors<string>.LoginProvider(entity) = value);
            loginProvider.SetAccessors(
                string (InternalEntityEntry entry) => IdentityUserTokenUnsafeAccessors<string>.LoginProvider(((IdentityUserToken<string>)(entry.Entity))),
                string (InternalEntityEntry entry) => IdentityUserTokenUnsafeAccessors<string>.LoginProvider(((IdentityUserToken<string>)(entry.Entity))),
                string (InternalEntityEntry entry) => entry.ReadOriginalValue<string>(loginProvider, 1),
                string (InternalEntityEntry entry) => entry.ReadRelationshipSnapshotValue<string>(loginProvider, 1),
                object (ValueBuffer valueBuffer) => valueBuffer[1]);
            loginProvider.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            loginProvider.TypeMapping = CosmosTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                clrType: typeof(string),
                jsonValueReaderWriter: JsonStringReaderWriter.Instance);
            loginProvider.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(loginProvider));

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(IdentityUserToken<string>).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserToken<string>).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            name.SetGetter(
                string (IdentityUserToken<string> entity) => IdentityUserTokenUnsafeAccessors<string>.Name(entity),
                bool (IdentityUserToken<string> entity) => IdentityUserTokenUnsafeAccessors<string>.Name(entity) == null,
                string (IdentityUserToken<string> instance) => IdentityUserTokenUnsafeAccessors<string>.Name(instance),
                bool (IdentityUserToken<string> instance) => IdentityUserTokenUnsafeAccessors<string>.Name(instance) == null);
            name.SetSetter(
                (IdentityUserToken<string> entity, string value) => IdentityUserTokenUnsafeAccessors<string>.Name(entity) = value);
            name.SetMaterializationSetter(
                (IdentityUserToken<string> entity, string value) => IdentityUserTokenUnsafeAccessors<string>.Name(entity) = value);
            name.SetAccessors(
                string (InternalEntityEntry entry) => IdentityUserTokenUnsafeAccessors<string>.Name(((IdentityUserToken<string>)(entry.Entity))),
                string (InternalEntityEntry entry) => IdentityUserTokenUnsafeAccessors<string>.Name(((IdentityUserToken<string>)(entry.Entity))),
                string (InternalEntityEntry entry) => entry.ReadOriginalValue<string>(name, 2),
                string (InternalEntityEntry entry) => entry.ReadRelationshipSnapshotValue<string>(name, 2),
                object (ValueBuffer valueBuffer) => valueBuffer[2]);
            name.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: 2,
                storeGenerationIndex: -1);
            name.TypeMapping = CosmosTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                clrType: typeof(string),
                jsonValueReaderWriter: JsonStringReaderWriter.Instance);
            name.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(name));

            var value = runtimeEntityType.AddProperty(
                "Value",
                typeof(string),
                propertyInfo: typeof(IdentityUserToken<string>).GetProperty("Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserToken<string>).GetField("<Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            value.SetGetter(
                string (IdentityUserToken<string> entity) => IdentityUserTokenUnsafeAccessors<string>.Value(entity),
                bool (IdentityUserToken<string> entity) => IdentityUserTokenUnsafeAccessors<string>.Value(entity) == null,
                string (IdentityUserToken<string> instance) => IdentityUserTokenUnsafeAccessors<string>.Value(instance),
                bool (IdentityUserToken<string> instance) => IdentityUserTokenUnsafeAccessors<string>.Value(instance) == null);
            value.SetSetter(
                (IdentityUserToken<string> entity, string value) => IdentityUserTokenUnsafeAccessors<string>.Value(entity) = value);
            value.SetMaterializationSetter(
                (IdentityUserToken<string> entity, string value) => IdentityUserTokenUnsafeAccessors<string>.Value(entity) = value);
            value.SetAccessors(
                string (InternalEntityEntry entry) => IdentityUserTokenUnsafeAccessors<string>.Value(((IdentityUserToken<string>)(entry.Entity))),
                string (InternalEntityEntry entry) => IdentityUserTokenUnsafeAccessors<string>.Value(((IdentityUserToken<string>)(entry.Entity))),
                string (InternalEntityEntry entry) => entry.ReadOriginalValue<string>(value, 3),
                string (InternalEntityEntry entry) => entry.GetCurrentValue<string>(value),
                object (ValueBuffer valueBuffer) => valueBuffer[3]);
            value.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            value.TypeMapping = CosmosTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                clrType: typeof(string),
                jsonValueReaderWriter: JsonStringReaderWriter.Instance);

            var __id = runtimeEntityType.AddProperty(
                "__id",
                typeof(string),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueGeneratorFactory: new IdValueGeneratorFactory().Create);
            __id.SetAccessors(
                string (InternalEntityEntry entry) => entry.ReadShadowValue<string>(0),
                string (InternalEntityEntry entry) => entry.ReadShadowValue<string>(0),
                string (InternalEntityEntry entry) => entry.ReadOriginalValue<string>(__id, 4),
                string (InternalEntityEntry entry) => entry.GetCurrentValue<string>(__id),
                object (ValueBuffer valueBuffer) => valueBuffer[4]);
            __id.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: 0,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            __id.TypeMapping = CosmosTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                clrType: typeof(string),
                jsonValueReaderWriter: JsonStringReaderWriter.Instance);
            __id.AddAnnotation("Cosmos:PropertyName", "id");

            var __jObject = runtimeEntityType.AddProperty(
                "__jObject",
                typeof(JObject),
                nullable: true,
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore);
            __jObject.SetAccessors(
                JObject (InternalEntityEntry entry) => (entry.FlaggedAsStoreGenerated(5) ? entry.ReadStoreGeneratedValue<JObject>(1) : (entry.FlaggedAsTemporary(5) && entry.ReadShadowValue<JObject>(1) == null ? entry.ReadTemporaryValue<JObject>(1) : entry.ReadShadowValue<JObject>(1))),
                JObject (InternalEntityEntry entry) => entry.ReadShadowValue<JObject>(1),
                JObject (InternalEntityEntry entry) => entry.ReadOriginalValue<JObject>(__jObject, 5),
                JObject (InternalEntityEntry entry) => entry.GetCurrentValue<JObject>(__jObject),
                object (ValueBuffer valueBuffer) => valueBuffer[5]);
            __jObject.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: 1,
                relationshipIndex: -1,
                storeGenerationIndex: 1);
            __jObject.TypeMapping = CosmosTypeMapping.Default.Clone(
                comparer: new ValueComparer<JObject>(
                    bool (JObject v1, JObject v2) => object.Equals(v1, v2),
                    int (JObject v) => ((object)v).GetHashCode(),
                    JObject (JObject v) => v),
                keyComparer: new ValueComparer<JObject>(
                    bool (JObject v1, JObject v2) => object.Equals(v1, v2),
                    int (JObject v) => ((object)v).GetHashCode(),
                    JObject (JObject v) => v),
                providerValueComparer: new ValueComparer<JObject>(
                    bool (JObject v1, JObject v2) => object.Equals(v1, v2),
                    int (JObject v) => ((object)v).GetHashCode(),
                    JObject (JObject v) => v),
                clrType: typeof(JObject));
            __jObject.AddAnnotation("Cosmos:PropertyName", "");

            var key = runtimeEntityType.AddKey(
                new[] { userId, loginProvider, name });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var userId = runtimeEntityType.FindProperty("UserId");
            var loginProvider = runtimeEntityType.FindProperty("LoginProvider");
            var name = runtimeEntityType.FindProperty("Name");
            var value = runtimeEntityType.FindProperty("Value");
            var __id = runtimeEntityType.FindProperty("__id");
            var __jObject = runtimeEntityType.FindProperty("__jObject");
            var key = runtimeEntityType.FindKey(new[] { userId, loginProvider, name });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateCompositeFactory(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<IReadOnlyList<object>>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((IdentityUserToken<string>)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string, string, string, string, JObject>((source.GetCurrentValue<string>(userId) == null ? null : ((ValueComparer<string>)(((IProperty)userId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(userId))), (source.GetCurrentValue<string>(loginProvider) == null ? null : ((ValueComparer<string>)(((IProperty)loginProvider).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(loginProvider))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), (source.GetCurrentValue<string>(value) == null ? null : ((ValueComparer<string>)(((IProperty)value).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(value))), (source.GetCurrentValue<string>(__id) == null ? null : ((ValueComparer<string>)(((IProperty)__id).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(__id))), (source.GetCurrentValue<JObject>(__jObject) == null ? null : ((ValueComparer<JObject>)(((IProperty)__jObject).GetValueComparer())).Snapshot(source.GetCurrentValue<JObject>(__jObject))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<string, JObject>((default(string) == null ? null : ((ValueComparer<string>)(((IProperty)userId).GetValueComparer())).Snapshot(default(string))), (default(JObject) == null ? null : ((ValueComparer<JObject>)(((IProperty)__jObject).GetValueComparer())).Snapshot(default(JObject)))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (InternalEntityEntry source) => ((ISnapshot)(new Snapshot<string, JObject>(default(string), default(JObject)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => ((ISnapshot)(new Snapshot<string, JObject>((source.ContainsKey("__id") ? ((string)(source["__id"])) : null), (source.ContainsKey("__jObject") ? ((JObject)(source["__jObject"])) : null)))));
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<string, JObject>(default(string), default(JObject)))));
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((IdentityUserToken<string>)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string, string>((source.GetCurrentValue<string>(userId) == null ? null : ((ValueComparer<string>)(((IProperty)userId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(userId))), (source.GetCurrentValue<string>(loginProvider) == null ? null : ((ValueComparer<string>)(((IProperty)loginProvider).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(loginProvider))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(name))))));
                });
            runtimeEntityType.Counts = new PropertyCounts(
                propertyCount: 6,
                navigationCount: 0,
                complexPropertyCount: 0,
                originalValueCount: 6,
                shadowCount: 2,
                relationshipCount: 3,
                storeGeneratedCount: 2);
            runtimeEntityType.AddAnnotation("Cosmos:ContainerName", "Identity_UserTokens");
            runtimeEntityType.AddAnnotation("Cosmos:PartitionKeyNames", new List<string> { "UserId" });
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AspNetUserTokens");

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}