// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Cosmos.Storage.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Newtonsoft.Json.Linq;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Mqtt.Server.Identity.CosmosDB.Compiled
{
    [EntityFrameworkInternal]
    public partial class IdentityRoleEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Microsoft.AspNetCore.Identity.IdentityRole",
                typeof(IdentityRole),
                baseEntityType,
                propertyCount: 5,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(string),
                propertyInfo: typeof(IdentityRole<string>).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityRole<string>).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            id.SetGetter(
                string (IdentityRole instance) => IdentityRoleUnsafeAccessors<string>.Id(instance),
                bool (IdentityRole instance) => IdentityRoleUnsafeAccessors<string>.Id(instance) == null);
            id.SetSetter(
                IdentityRole (IdentityRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<string>.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                IdentityRole (IdentityRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<string>.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<string>.Id(((IdentityRole)(entry.Entity))),
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<string>.Id(((IdentityRole)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(id, 0),
                string (IInternalEntry entry) => ((InternalEntityEntry)(entry)).ReadRelationshipSnapshotValue<string>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            id.TypeMapping = CosmosTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                clrType: typeof(string),
                jsonValueReaderWriter: JsonStringReaderWriter.Instance);
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(id));
            id.AddAnnotation("Cosmos:PropertyName", "id");

            var concurrencyStamp = runtimeEntityType.AddProperty(
                "ConcurrencyStamp",
                typeof(string),
                propertyInfo: typeof(IdentityRole<string>).GetProperty("ConcurrencyStamp", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityRole<string>).GetField("<ConcurrencyStamp>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                concurrencyToken: true,
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore);
            concurrencyStamp.SetGetter(
                string (IdentityRole instance) => IdentityRoleUnsafeAccessors<string>.ConcurrencyStamp(instance),
                bool (IdentityRole instance) => IdentityRoleUnsafeAccessors<string>.ConcurrencyStamp(instance) == null);
            concurrencyStamp.SetSetter(
                IdentityRole (IdentityRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<string>.ConcurrencyStamp(instance) = value;
                    return instance;
                });
            concurrencyStamp.SetMaterializationSetter(
                IdentityRole (IdentityRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<string>.ConcurrencyStamp(instance) = value;
                    return instance;
                });
            concurrencyStamp.SetAccessors(
                string (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(1) ? entry.ReadStoreGeneratedValue<string>(0) : (entry.FlaggedAsTemporary(1) && IdentityRoleUnsafeAccessors<string>.ConcurrencyStamp(((IdentityRole)(entry.Entity))) == null ? entry.ReadTemporaryValue<string>(0) : IdentityRoleUnsafeAccessors<string>.ConcurrencyStamp(((IdentityRole)(entry.Entity))))),
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<string>.ConcurrencyStamp(((IdentityRole)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(concurrencyStamp, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(concurrencyStamp));
            concurrencyStamp.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: 0);
            concurrencyStamp.TypeMapping = CosmosTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                clrType: typeof(string),
                jsonValueReaderWriter: JsonStringReaderWriter.Instance);
            concurrencyStamp.AddAnnotation("Cosmos:PropertyName", "_etag");

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(IdentityRole<string>).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityRole<string>).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 256);
            name.SetGetter(
                string (IdentityRole instance) => IdentityRoleUnsafeAccessors<string>.Name(instance),
                bool (IdentityRole instance) => IdentityRoleUnsafeAccessors<string>.Name(instance) == null);
            name.SetSetter(
                IdentityRole (IdentityRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<string>.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                IdentityRole (IdentityRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<string>.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<string>.Name(((IdentityRole)(entry.Entity))),
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<string>.Name(((IdentityRole)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
            name.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            name.TypeMapping = CosmosTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                clrType: typeof(string),
                jsonValueReaderWriter: JsonStringReaderWriter.Instance);

            var normalizedName = runtimeEntityType.AddProperty(
                "NormalizedName",
                typeof(string),
                propertyInfo: typeof(IdentityRole<string>).GetProperty("NormalizedName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityRole<string>).GetField("<NormalizedName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 256);
            normalizedName.SetGetter(
                string (IdentityRole instance) => IdentityRoleUnsafeAccessors<string>.NormalizedName(instance),
                bool (IdentityRole instance) => IdentityRoleUnsafeAccessors<string>.NormalizedName(instance) == null);
            normalizedName.SetSetter(
                IdentityRole (IdentityRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<string>.NormalizedName(instance) = value;
                    return instance;
                });
            normalizedName.SetMaterializationSetter(
                IdentityRole (IdentityRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<string>.NormalizedName(instance) = value;
                    return instance;
                });
            normalizedName.SetAccessors(
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<string>.NormalizedName(((IdentityRole)(entry.Entity))),
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<string>.NormalizedName(((IdentityRole)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(normalizedName, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(normalizedName));
            normalizedName.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            normalizedName.TypeMapping = CosmosTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                clrType: typeof(string),
                jsonValueReaderWriter: JsonStringReaderWriter.Instance);

            var __jObject = runtimeEntityType.AddProperty(
                "__jObject",
                typeof(JObject),
                nullable: true,
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore);
            __jObject.SetAccessors(
                JObject (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(4) ? entry.ReadStoreGeneratedValue<JObject>(1) : (entry.FlaggedAsTemporary(4) && entry.ReadShadowValue<JObject>(0) == null ? entry.ReadTemporaryValue<JObject>(1) : entry.ReadShadowValue<JObject>(0))),
                JObject (IInternalEntry entry) => entry.ReadShadowValue<JObject>(0),
                JObject (IInternalEntry entry) => entry.ReadOriginalValue<JObject>(__jObject, 4),
                JObject (IInternalEntry entry) => entry.GetCurrentValue<JObject>(__jObject));
            __jObject.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: 0,
                relationshipIndex: -1,
                storeGenerationIndex: 1);
            __jObject.TypeMapping = CosmosTypeMapping.Default.Clone(
                comparer: new ValueComparer<JObject>(
                    bool (JObject v1, JObject v2) => object.Equals(v1, v2),
                    int (JObject v) => ((object)v).GetHashCode(),
                    JObject (JObject v) => v),
                keyComparer: new ValueComparer<JObject>(
                    bool (JObject v1, JObject v2) => object.Equals(v1, v2),
                    int (JObject v) => ((object)v).GetHashCode(),
                    JObject (JObject v) => v),
                providerValueComparer: new ValueComparer<JObject>(
                    bool (JObject v1, JObject v2) => object.Equals(v1, v2),
                    int (JObject v) => ((object)v).GetHashCode(),
                    JObject (JObject v) => v),
                clrType: typeof(JObject));
            __jObject.AddAnnotation("Cosmos:PropertyName", "");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var concurrencyStamp = runtimeEntityType.FindProperty("ConcurrencyStamp");
            var name = runtimeEntityType.FindProperty("Name");
            var normalizedName = runtimeEntityType.FindProperty("NormalizedName");
            var __jObject = runtimeEntityType.FindProperty("__jObject");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNullableFactory<string, int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<string>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityRole)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string, string, string, JObject>((source.GetCurrentValue<string>(id) == null ? null : ((ValueComparer<string>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(id))), (source.GetCurrentValue<string>(concurrencyStamp) == null ? null : ((ValueComparer<string>)(((IProperty)concurrencyStamp).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(concurrencyStamp))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), (source.GetCurrentValue<string>(normalizedName) == null ? null : ((ValueComparer<string>)(((IProperty)normalizedName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(normalizedName))), (source.GetCurrentValue<JObject>(__jObject) == null ? null : ((ValueComparer<JObject>)(((IProperty)__jObject).GetValueComparer())).Snapshot(source.GetCurrentValue<JObject>(__jObject))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<string, JObject>((default(string) == null ? null : ((ValueComparer<string>)(((IProperty)concurrencyStamp).GetValueComparer())).Snapshot(default(string))), (default(JObject) == null ? null : ((ValueComparer<JObject>)(((IProperty)__jObject).GetValueComparer())).Snapshot(default(JObject)))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<string, JObject>(default(string), default(JObject)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => ((ISnapshot)(new Snapshot<JObject>((source.ContainsKey("__jObject") ? ((JObject)(source["__jObject"])) : null)))));
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<JObject>(default(JObject)))));
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityRole)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string>((source.GetCurrentValue<string>(id) == null ? null : ((ValueComparer<string>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(id))))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 5,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 5,
                shadowCount: 1,
                relationshipCount: 1,
                storeGeneratedCount: 2));
            runtimeEntityType.AddAnnotation("Cosmos:ContainerName", "Identity_Roles");
            runtimeEntityType.AddAnnotation("Cosmos:ETagName", "ConcurrencyStamp");
            runtimeEntityType.AddAnnotation("Cosmos:PartitionKeyNames", new List<string> { "Id" });
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AspNetRoles");

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}