changelog:
  exclude:
    labels:
      - wontfix
      - question
      - experimental
      - epic
      - duplicate
  categories:
    - title: Features
      labels: 
        - feature
    - title: Enchancements
      labels: 
        - enhancement
      exclude:
        labels:
          - feature
          - bug
    - title: Bug-fixes
      labels:
        - bug
    - title: Documentation updates
      labels:
        - documentation
    - title: Other changes
      labels:
        - *
