// <auto-generated />
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Mqtt.Server.Identity.SqlServer.Compiled
{
    [EntityFrameworkInternal]
    public partial class IdentityUserPasskeyEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>",
                typeof(IdentityUserPasskey<string>),
                baseEntityType,
                propertyCount: 2,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var credentialId = runtimeEntityType.AddProperty(
                "CredentialId",
                typeof(byte[]),
                propertyInfo: typeof(IdentityUserPasskey<string>).GetProperty("CredentialId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserPasskey<string>).GetField("<CredentialId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 1024);
            credentialId.SetGetter(
                byte[] (IdentityUserPasskey<string> instance) => IdentityUserPasskeyUnsafeAccessors<string>.CredentialId(instance),
                bool (IdentityUserPasskey<string> instance) => IdentityUserPasskeyUnsafeAccessors<string>.CredentialId(instance) == null);
            credentialId.SetSetter(
                IdentityUserPasskey<string> (IdentityUserPasskey<string> instance, byte[] value) =>
                {
                    IdentityUserPasskeyUnsafeAccessors<string>.CredentialId(instance) = value;
                    return instance;
                });
            credentialId.SetMaterializationSetter(
                IdentityUserPasskey<string> (IdentityUserPasskey<string> instance, byte[] value) =>
                {
                    IdentityUserPasskeyUnsafeAccessors<string>.CredentialId(instance) = value;
                    return instance;
                });
            credentialId.SetAccessors(
                byte[] (IInternalEntry entry) => IdentityUserPasskeyUnsafeAccessors<string>.CredentialId(((IdentityUserPasskey<string>)(entry.Entity))),
                byte[] (IInternalEntry entry) => IdentityUserPasskeyUnsafeAccessors<string>.CredentialId(((IdentityUserPasskey<string>)(entry.Entity))),
                byte[] (IInternalEntry entry) => entry.ReadOriginalValue<byte[]>(credentialId, 0),
                byte[] (IInternalEntry entry) => ((InternalEntityEntry)(entry)).ReadRelationshipSnapshotValue<byte[]>(credentialId, 0));
            credentialId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            credentialId.TypeMapping = SqlServerByteArrayTypeMapping.Default.Clone(
                comparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)(v1)), ((object)(v2))),
                    int (byte[] v) => ((object)v).GetHashCode(),
                    byte[] (byte[] v) => v),
                keyComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)(v1)), ((object)(v2))),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)(v))),
                    byte[] (byte[] source) => source.ToArray()),
                providerValueComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)(v1)), ((object)(v2))),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)(v))),
                    byte[] (byte[] source) => source.ToArray()),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "varbinary(1024)",
                    size: 1024));
            credentialId.SetCurrentValueComparer(new StructuralEntryCurrentValueComparer(credentialId));
            credentialId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var userId = runtimeEntityType.AddProperty(
                "UserId",
                typeof(string),
                propertyInfo: typeof(IdentityUserPasskey<string>).GetProperty("UserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserPasskey<string>).GetField("<UserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            userId.SetGetter(
                string (IdentityUserPasskey<string> instance) => IdentityUserPasskeyUnsafeAccessors<string>.UserId(instance),
                bool (IdentityUserPasskey<string> instance) => IdentityUserPasskeyUnsafeAccessors<string>.UserId(instance) == null);
            userId.SetSetter(
                IdentityUserPasskey<string> (IdentityUserPasskey<string> instance, string value) =>
                {
                    IdentityUserPasskeyUnsafeAccessors<string>.UserId(instance) = value;
                    return instance;
                });
            userId.SetMaterializationSetter(
                IdentityUserPasskey<string> (IdentityUserPasskey<string> instance, string value) =>
                {
                    IdentityUserPasskeyUnsafeAccessors<string>.UserId(instance) = value;
                    return instance;
                });
            userId.SetAccessors(
                string (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(1) ? entry.ReadStoreGeneratedValue<string>(0) : (entry.FlaggedAsTemporary(1) && IdentityUserPasskeyUnsafeAccessors<string>.UserId(((IdentityUserPasskey<string>)(entry.Entity))) == null ? entry.ReadTemporaryValue<string>(0) : IdentityUserPasskeyUnsafeAccessors<string>.UserId(((IdentityUserPasskey<string>)(entry.Entity))))),
                string (IInternalEntry entry) => IdentityUserPasskeyUnsafeAccessors<string>.UserId(((IdentityUserPasskey<string>)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(userId, 1),
                string (IInternalEntry entry) => ((InternalEntityEntry)(entry)).ReadRelationshipSnapshotValue<string>(userId, 1));
            userId.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: 0);
            userId.TypeMapping = SqlServerStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string l, string r) => string.Equals(l, r, StringComparison.OrdinalIgnoreCase),
                    int (string v) => (v == null ? 0 : StringComparer.OrdinalIgnoreCase.GetHashCode(v)),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string l, string r) => string.Equals(l, r, StringComparison.OrdinalIgnoreCase),
                    int (string v) => (v == null ? 0 : StringComparer.OrdinalIgnoreCase.GetHashCode(v)),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string l, string r) => string.Equals(l, r, StringComparison.OrdinalIgnoreCase),
                    int (string v) => (v == null ? 0 : StringComparer.OrdinalIgnoreCase.GetHashCode(v)),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "nvarchar(450)",
                    size: 450,
                    unicode: true,
                    dbType: System.Data.DbType.String));
            userId.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(userId));
            userId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { credentialId });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { userId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var credentialId = runtimeEntityType.FindProperty("CredentialId");
            var userId = runtimeEntityType.FindProperty("UserId");
            var key = runtimeEntityType.FindKey(new[] { credentialId });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNullableFactory<byte[], int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<byte[]>(key));
            var data = runtimeEntityType.FindNavigation("Data");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityUserPasskey<string>)(source.Entity));
                    return ((ISnapshot)(new Snapshot<byte[], string>((source.GetCurrentValue<byte[]>(credentialId) == null ? null : ((ValueComparer<byte[]>)(((IProperty)credentialId).GetValueComparer())).Snapshot(source.GetCurrentValue<byte[]>(credentialId))), (source.GetCurrentValue<string>(userId) == null ? null : ((ValueComparer<string>)(((IProperty)userId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(userId))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<string>((default(string) == null ? null : ((ValueComparer<string>)(((IProperty)userId).GetValueComparer())).Snapshot(default(string)))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<string>(default(string)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityUserPasskey<string>)(source.Entity));
                    return ((ISnapshot)(new Snapshot<byte[], string, object>((source.GetCurrentValue<byte[]>(credentialId) == null ? null : ((ValueComparer<byte[]>)(((IProperty)credentialId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<byte[]>(credentialId))), (source.GetCurrentValue<string>(userId) == null ? null : ((ValueComparer<string>)(((IProperty)userId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(userId))), source.GetCurrentValue<IdentityPasskeyData>(data))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 2,
                navigationCount: 1,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 2,
                shadowCount: 0,
                relationshipCount: 3,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AspNetUserPasskeys");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}