name: Publish mqtt-server app

on:
  workflow_dispatch:

env:
  PROJECT_PATH: ./Mqtt.Server/Mqtt.Server.csproj
  FRAMEWORK: net10.0
  RIDS: linux-x64;linux-arm64;osx-x64;osx-arm64;win-x64;win-arm64

jobs:
  test:
    name: Build and run unit tests
    uses: ./.github/workflows/dotnet-build-test.yml

  release:
    name: Create release
    runs-on: ubuntu-latest
    
    if: contains(github.ref, 'tags/v')

    needs: [test]

    steps:
    - name: Create release notes
      id: create_release_notes
      uses: Lapiniot/create-release-notes@v1.0.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}

    - name: Create release
      id: create_release
      uses: Lapiniot/create-release@v1.0.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body: ${{ steps.create_release_notes.outputs.release_notes_content }}
        draft: true
        prerelease: false
        generate_release_notes: false
    
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}

  publish:
    name: Build and publish artifacts
    runs-on: ubuntu-latest

    needs: [test, release]

    if: always() && !cancelled() && needs.test.result == 'success'

    steps:
    - name: Checkout project files
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'npm'
        cache-dependency-path: ./Mqtt.Server.Web/package-lock.json

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Install all the dependencies from package.json
      run: npm ci
      working-directory: ./Mqtt.Server.Web

    - name: Restore .NET dependencies
      run: dotnet restore "${{ env.PROJECT_PATH }}" /p:RuntimeIdentifiers='"${{env.RIDS}}"'

    - name: .NET Publish
      run: | 
        printf "${{env.RIDS}}" | tr ';' '\0' | xargs -0 -n 1 -I {RID} dotnet publish "${{ env.PROJECT_PATH }}" \
        --no-restore -f ${{env.FRAMEWORK}} -c Release -r {RID} \
        /p:SelfContained=true /p:PublishTrimmed=true /p:SuppressTrimAnalysisWarnings=true
        
        printf "${{env.RIDS}}" | tr ';' '\0' | xargs -0 -n 1 -I {RID} bash -c "\
        cd ./artifacts/publish/Mqtt.Server/release_${{env.FRAMEWORK}}_{RID} && \
        zip -r9 ../../mqtt-server.{RID}.zip ."

    - name: Upload artifact 'mqtt-server.linux-x64.zip'
      uses: actions/upload-artifact@v7
      with:
        name: mqtt-server.linux-x64.zip
        path: ./artifacts/publish/mqtt-server.linux-x64.zip
        archive: false

    - name: Upload artifact 'mqtt-server.linux-arm64.zip'
      uses: actions/upload-artifact@v7
      with:
        name: mqtt-server.linux-arm64.zip
        path: ./artifacts/publish/mqtt-server.linux-arm64.zip
        archive: false

    - name: Upload artifact 'mqtt-server.osx-x64.zip'
      uses: actions/upload-artifact@v7
      with:
        name: mqtt-server.osx-x64.zip
        path: ./artifacts/publish/mqtt-server.osx-x64.zip
        archive: false

    - name: Upload artifact 'mqtt-server.osx-arm64.zip'
      uses: actions/upload-artifact@v7
      with:
        name: mqtt-server.osx-arm64.zip
        path: ./artifacts/publish/mqtt-server.osx-arm64.zip
        archive: false

    - name: Upload artifact 'mqtt-server.win-x64.zip'
      uses: actions/upload-artifact@v7
      with:
        name: mqtt-server.win-x64.zip
        path: ./artifacts/publish/mqtt-server.win-x64.zip
        archive: false

    - name: Upload artifact 'mqtt-server.win-arm64.zip'
      uses: actions/upload-artifact@v7
      with:
        name: mqtt-server.win-arm64.zip
        path: ./artifacts/publish/mqtt-server.win-arm64.zip
        archive: false

    - name: Upload release assets
      if: needs.release.result == 'success'
      uses: Lapiniot/upload-release-asset@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        release_id: ${{ needs.release.outputs.release_id }}
        path: ./artifacts/publish/mqtt-server.*.zip
        label: mqtt-server
        include-hidden-files: false
        content_type: application/zip