name: Pack and push to GitHub package repository
description: |
  This workflow is designed to build, pack and push libraries to the GitHub package 
  repository and performs following steps:
  - Build and pack packageable projects as Nuget packages
  - Push packages to the GitHub Nuget package repository

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Build and run tests ]
    types: [ completed ]

env:
  FRAMEWORK: net10.0
  RIDS: linux-x64;linux-arm64;osx-x64;osx-arm64;win-x64;win-arm64

jobs:
  publish:
    name: Build and publish Nuget packages
    runs-on: ubuntu-latest

    if: contains(github.event.workflow_run.head_branch, 'tags/v') && github.event.workflow_run.conclusion == 'success'

    steps:
    - name: Checkout project files
      uses: actions/checkout@v6
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
        submodules: recursive

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'npm'
        cache-dependency-path: ./Mqtt.Server.Web/package-lock.json

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ vars.NET10_SDK_VERSION || '10.0.x' }}

    - name: Install all the dependencies from package.json
      run: npm ci
      working-directory: ./Mqtt.Server.Web

    - name: .NET Pack Libraries
      run: | 
        dotnet pack Net.Mqtt.Libs.slnf -c Release

    - name: .NET Pack Tools
      run: | 
        dotnet pack Net.Mqtt.Tools.slnf -c Release \
        /p:TargetFrameworks=${{ env.FRAMEWORK }} \
        /p:RuntimeIdentifiers='"${{ env.RIDS }}"' \
        /p:SelfContained=true \
        /p:PublishTrimmed=true \
        /p:SuppressTrimAnalysisWarnings=true

    - name: Upload build artifacts
      uses: Lapiniot/upload-artifact@v1
      with:
        path: ./artifacts/package/release/*.nupkg
        archive: false
        if-no-files-found: error

    - name: Push packages to GitHub Nuget feed
      run: |
        dotnet nuget push "./artifacts/package/release/*.nupkg" \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --api-key ${GITHUB_TOKEN} --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}