# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish mqtt-server app

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
  
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime-id: [linux-x64, linux-arm64, osx-x64, osx-arm64, win-x64, win-arm64]
    needs: build
    steps:
    - name: Publish
      run: dotnet publish --no-build -r ${{matrix.runtime-id}} -p:SelfContained=true -p:PublishTrimmed=true -p:SuppressTrimAnalysisWarnings=true ./Mqtt.Server/Mqtt.Server.csproj
